//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackieTestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_Unit
    {
        public int Unit_Id { get; set; }
        public string Unit_Name { get; set; }
        public string Unit_Description { get; set; }
        public Nullable<System.DateTime> Unit_CreatedDate { get; set; }
        public string Unit_CreatedBy { get; set; }
        public Nullable<System.DateTime> Unit_ModifiedDate { get; set; }
        public string Unit_ModifiedBy { get; set; }
        public string Unit_History { get; set; }
        public Nullable<bool> Unit_IsActive { get; set; }
    }
}
